name: vpn_app
description: vpn app made with flutter and ovpn library.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  change_app_package_name: ^1.0.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  package_info: ^0.4.3
  introduction_screen: ^2.1.0
  flag: ^5.0.1
  country_icons: ^2.0.2
  firebase_core: "^0.7.0"
  firebase_auth: "^0.20.1"
  shared_preferences: ^2.0.6
  provider: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - "assets/"
    - "assets/vpn/"
   